# Usa una imagen oficial de Node.js LTS como base
FROM node:lts-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json al contenedor
COPY package*.json ./

# Instala todas las dependencias, incluidas las de desarrollo
RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Expone el puerto en el que se ejecutará la aplicación
EXPOSE 3000

# Comando para ejecutar la aplicación utilizando ts-node-dev para reiniciar automáticamente el servidor cuando se realizan cambios en el código
CMD ["npm", "run", "dev"]
